@startuml

title Panda steps

skinparam linestyle ortho
rectangle "panda: JumpyPanda" as p
rectangle "target: Tile" as t1
rectangle "pandaStangingOn: Tile" as t2

p -right-> t2: accept(panda)
t2-down->t1: setCurrentAnimal(null)
t2-left->p: setStandingOn(target)
t2->t2: setCurrentAnimal(p)

@enduml