@startuml

title Panda falls down in line

participant "panda: JumpyPanda" as panda
participant ": Level" as level
participant "target: Tile" as target
participant "orangutan: Orangutan" as orangutan
participant "secondPanda: CowardPanda" as secondPanda
participant "lastPanda: SleepyPanda" as lastPanda

note over panda
    A target csempe isFragile változójának
    értéke true, a life mezeje pedig 0.
    Amikor a panda odamozog, akkor meghal.
    Ebben az esetben a panda mögött található
    még egy 2 pandából álló lánc, ez a panda
    halála előtt felbomlik. A panda-t vezető
    állat jelen esetben az orángután.
end note

[-> panda : moveTo (target)
activate panda

panda -> target ++ : accept (panda)

target -> panda ++ : kill ()

panda -> panda ++ : stopLeading ()

panda -> orangutan ++ : setGuidedAnimal (null)
panda <-- orangutan --

panda -> secondPanda ++ : stopLeading ()

secondPanda -> panda ++ : setGuidedAnimal (null)
secondPanda <-- panda --

secondPanda -> lastPanda ++ : stopLeading ()

lastPanda -> secondPanda ++ : setGuidedAnimal (null)
lastPanda <-- secondPanda --

lastPanda -> lastPanda ++ : setLeaderAnimal (null)
lastPanda <-- lastPanda --

secondPanda <-- lastPanda --

secondPanda -> secondPanda ++ : setLeaderAnimal (null)
secondPanda <-- secondPanda --

panda <-- secondPanda --

panda -> panda ++ : setLeaderAnimal (null)
panda <-- panda --

panda <-- panda --

panda -> level ++ : removeAnimal (panda)
panda <-- level --

target <-- panda --

panda <-- target -- : true

[<-- panda
deactivate panda

@enduml