@startuml
title Panda gets scared alone

participant "w : BeepWave" as w

participant "p: CowardPanda" as p2

note over w
Jelen esetben a panda szabadon áll,
nem vezet senkit és nincs vezetve.
end note

[->w: hit(p)
activate w



w->p2 ++: scare()



p2-->w --

[<-- w
deactivate w

@enduml