@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

class Tile {
    +life: int
    +isFragile: boolean
    +accept (animal: Animal): boolean
    +damage (): void
}

Tile "0..n" -- Tile : +neighbours

interface Updatable {
    +update (): void
}

abstract class Animal {
    +startLeading (leader: Animal): void
    +stopLeading (): void
    +kill (): void
    +moveTo (targetTile: Tile): void
    +use (item: Item): void
}

Tile <-- Animal : -standingOn
Animal "0..1" -- Tile : -currentAnimal

abstract class Item {
    -placedOn: Tile
    +use (user: Animal): void
}

Tile <-- Item : -placedOn
Item "0..1" -- Tile : -placedItem

Updatable <|.. Animal
Updatable <|.. Item

class Level {
}

Tile "0..n" *-- Level : tiles

class Panda {
}

class Orangutan {
}

Animal <|-- Panda
Animal <|-- Orangutan

class Couch {

}

Panda "0..1" -- Couch : -sleepingPanda
Couch -- "0..1" Panda : -sleepingIn

class GameMachine {
}

class ChocolateVendingMachine {
}

class Wardrobe {
}

Item <|-- Couch
Item <|-- GameMachine
Item <|-- ChocolateVendingMachine
Item <|-- Wardrobe

class Portal {
    +enter (animal: Animal): void
}

Portal <-- Portal : +otherEnd
Tile <-- Portal: +place

@enduml