@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

' ==========
' Interfaces
' ==========

interface Updatable {
    +update (): void
}

' =======
' Classes
' =======

class Timer <<singleton>> {
    +tick (): void
    +add (updatable: Updatable): void
    +remove (updatable: Updatable): void
}

class Level {
    +removeAnimal (animal: Animal): void
}

class Tile {
    +life: int
    +isFragile: boolean
    +accept (animal: Animal): boolean
    +damage (): void
    +spawnWave (wave: Wave): void
    +pushwave (wave: Wave): void
}

abstract class Animal {
    +startLeading (leader: Animal): void
    +stopLeading (): void
    +kill (): void
    +moveTo (targetTile: Tile): void
    +use (item: Item): void
    +update (): void
    +collideWithAnimal (animal: Animal): void
    +collideWithPanda (panda: Animal): void
    +collideWithOrangutan (orangutan: Orangutan): void
    +goToSleep(): void
    +jump(): void
    +scare(): void
}

abstract class Item {
    -placedOn: Tile
    +use (user: Animal): void
    +update (): void
}

abstract class Panda {
    +collideWithAnimal (animal: Animal): void
    +collideWithOrangutan (orangutan: Animal): void
}

class SleepyPanda {
    +goToSleep(): void
}

class JumpyPanda {
    +jump(): void
}

class CowardPanda {
    +scare(): void
}

class Orangutan {
    +collideWithAnimal (animal: Animal): void
}

class Couch {
    +use (user: Animal): void
    +update (): void
}

class GameMachine {
    +update (): void
}

class ChocolateVendingMachine {
    +update (): void
}

class Wardrobe {
    +use (user: Animal): void
}

class Portal {
    +enter (animal: Animal): void
}

abstract class Wave {
    -origin: Type
    +hit(animal: Animal): void
}

class SleepyWave{
    +hit(animal: Animal): void
}

class BeepWave{
    +hit(animal: Animal): void
}

class JumpyWave{
    +hit(animal: Animal): void
}
' ===========
' Inheritance
' ===========

Updatable <|.. Animal
Updatable <|.. Item

Animal <|-- Panda
Panda<|-- SleepyPanda
Panda<|-- JumpyPanda
Panda<|-- CowardPanda
Animal <|-- Orangutan

Item <|-- Couch
Item <|-- GameMachine
Item <|-- ChocolateVendingMachine
Item <|-- Wardrobe

Wave<|-- JumpyWave
Wave<|-- SleepyWave
Wave<|-- BeepWave

' ============
' Compositions
' ============

Updatable "0..n" *-- Timer : updatables
Tile "0..n" *-- Level : -tiles
Animal "0..n" *-- Level : -animals

' ============
' Associations
' ============

Tile "0..n" -- Tile : +neighbours

Tile <-- Animal : -standingOn
Animal "0..1" -- Tile : -currentAnimal

Animal "0..1" <-- Animal : leaderAnimal
Animal "0..1" <-- Animal : guidedAnimal

Tile <-- Item : -placedOn
Item "0..1" -- Tile : -placedItem

Panda "0..1" -- Couch : -sleepingPanda
Couch -- "0..1" Panda : -sleepingIn

Tile <-- Wave : +origin

Portal <-- Portal : +otherEnd
Tile <-- Portal : +place

Portal <-- Wardrobe : -portal


Tile <-- Level : +startTile
Tile <-- Level : +exitTile

@enduml