@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "a : Animal" as a
participant ": Game" as Game
participant "l : Level" as l

[-> a : kill ()
activate a

a -> Game ++ : getLevel ()
Game --> a -- : l

a -> l ++ : removeAnimal (a)
l --> a --

[<-- a
deactivate a

@enduml