@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "p : Portal" as p
participant "a : Animal" as a
participant "o : Portal" as o
participant "t : Tile" as t

[-> p : enter (a)
activate p

p -> p ++ : getOtherEnd ()
p --> p -- : o

p -> o ++ : getPlace ()
o --> p -- : t

p -> t ++ : accept (a)
t --> p --

[<-- p
deactivate p

@enduml