@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "t : Tile" as t
participant "a : Animal" as a

[-> t : accept(a)
activate t

opt Tile is broken

t -> a ++ : kill()
a --> t --

end

[<-- t
deactivate t

@enduml