@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "c : Couch" as c
participant "w : SleepyWave" as w
participant "placedOn : Tile" as t

[-> c : update ()
activate c

c -> w ** : new




c -> t ++ : spawnWave (w)
t --> c --

[<-- c
deactivate c

@enduml