@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "m : ChocolateVendingMachine" as m
participant "w : JumpyWave" as w
participant "placedOn : Tile" as t

[-> m : update ()
activate m

opt random

    m -> w ** : new



    m -> w ++ : setOrigin (t)
    w --> m --
    m -> t ++ : spawnWave (w)
    t --> m --

end

[<-- m
deactivate m

@enduml