@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "o : Orangutan" as o
participant ": Game" as Game

[-> o : kill ()
activate o

o -> Game ++ : gameOver ()
Game --> o --

[<-- o
deactivate o

@enduml