@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "m : ChocolateVendingMachine" as m
participant "w : Wave" as w
participant "t : Tile" as t

[-> m : update ()
activate m

opt random

    m -> w ** : new

    m -> w ++ : setType (BEEPING)
    w --> m --

    m -> m ++ : getPlacedOn ()
    m --> m -- : t

    m -> t ++ : spawnWave (w)
    t --> m --

end

[<-- m
deactivate m

@enduml