@startuml
participant "p : Panda" as p
participant "guidedAnimal : Panda" as guided

[-> p : stopLeading()
activate p


opt guidedAnimal != null

    p -> guided ++ : stopLeading ()
    guided --> p --

end

p -> p ++ : setLeaderAnimal (NULL)
p --> p --

p -> p ++ : setGuidedAnimal (NULL)
p --> p --

[<--p
deactivate p



@enduml