@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "a : Animal" as a
participant "t : Tile" as t
participant "currentAnimal : Animal" as currentAnimal
participant "guidedAnimal : Animal" as guidedAnimal
participant "standingOn : Tile" as standingOn

[-> a : moveTo (t)
activate a

a -> t ++ : accept (a)

opt currentAnimal != null

    t -> a ++ : collideWithAnimal (t.currentAnimal)
    a --> t --

    t --> a : false

else

    opt life == 0

        t -> a ++ : kill ()
        a --> t --

        t --> a : true

    end

    t -> a ++ : getStandingOn ()
    a --> t -- : standingOn

    opt a.guidedAnimal !=null
    a -> guidedAnimal ++: moveTo(standingOn)
    guidedAnimal --> a --
    end

    t -> standingOn ++ : setCurrentAnimal (null)
    standingOn --> t --

    t -> a ++ : setStandingOn (t)
    a --> t --

    t -> t ++ : setCurrentAnimal (a)
    t --> t --

    t --> a -- : true

end

[<-- a
deactivate a

@enduml