@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant ": Timer" as Timer
participant "u : Updatable" as u

[-> Timer : tick ()
activate Timer

loop for all u : Updatable
    Timer -> u ++ : update ()
    u --> Timer --
end

[<- Timer
deactivate Timer

@enduml