@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

:PandaController: <<internal>> as c
:Level: <<internal>> as l
:Player: as p

c -> (Panda steps)
l -> (Panda steps)
p -> (Orangutan steps)
l -> (Orangutan steps)
c -> (Orangutan steps with pandas behind)
l -> (Orangutan steps with pandas behind)
p -> (Orangutan steps with pandas behind)
c -> (Orangutan grabs first panda)
p -> (Orangutan grabs first panda)
c -> (Orangutan grabs another panda)
p -> (Orangutan grabs another panda)
p -> (Panda gets scared in line)
l -> (Panda gets scared in line)
p -> (Panda gets scared alone)
l -> (Panda gets scared alone)
c -> (Orangutan leads pandas out)
l -> (Orangutan leads pandas out)
p -> (Orangutan leads pandas out)
p -> (Panda falls down)
c -> (Panda falls down)
l -> (Panda falls down)
p -> (Orangutan falls down)
l -> (Orangutan falls down)
c -> (Panda sleeps)
l -> (Panda sleeps)
c -> (Panda gets scared)
l -> (Panda gets scared)
c -> (Panda jumps)
l -> (Panda jumps)
c -> (Panda collides with panda)
l -> (Panda collides with panda)

@enduml