@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "t : Tile" as t
participant "a : Animal" as a



[-> t : accept(a)
activate t



t -> a ++ : kill()
a -> a++  :stopLeading()
        a--> a--



a --> t --



[<-- t
deactivate t

@enduml