@startuml

title Panda steps

'This is a single line comment

participant "panda: JumpyPanda" as panda
participant "target: Tile" as target
participant "pandaStandingOn: Tile" as pandaStandingOn

note over panda
    Ebben az esetben a panda egy JumpyPanda, 
    és nincs általa vezetett állata. A 
    pandaStandingOn-t a 
    panda.getStandingOn () függvényhívással
    kaphatjuk meg
end note

[-> panda : moveTo (target)
activate panda

panda -> target ++ : accept (panda)

target -> pandaStandingOn ++ : setCurrentAnimal (null)
target <-- pandaStandingOn --

target -> panda ++ : setStandingOn (target)
target <-- panda --

target -> target ++ : setCurrentAnimal (panda)
target <-- target --

panda <-- target -- : true

[<-- panda
deactivate panda

@enduml