@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "w : Wardrobe" as w
participant "o : Wardrobe" as o
participant "a : Animal" as a
participant "t : Tile" as t

[-> w : use (a)
activate w

w -> o ++ : getPlacedOn()
o -> w -- : t

w -> a ++ : moveTo (t)
a --> w --

[<-- w
deactivate w

@enduml