@startuml
participant "exitTile: Tile" as exit
participant "startTile: Tile" as entry
participant "p : Animal" as p
participant "o: Animal" as o

[-> exit : accept(o)
activate exit
opt exitTile is the exit tile
exit -> o ++ : getGuidedAnimal()
o --> exit -- : p

exit -> entry ++ : accept(o)
entry --> exit -- :

exit -> p ++ : leadOut()
p -> exit --
end

[<--exit
deactivate exit

@enduml