@startuml

skinparam classAttributeIconSize 0
skinparam guillemet false

participant "t : Tile" as t
participant "w : Wave" as w
participant "neighbour : Tile" as neighbour
participant "a: Animal" as a

[-> t : spawnWave (w)
activate t

t -> w ++ : setOrigin (t)
w --> t --

loop for all neighbour : Tile

    t -> neighbour ++ : getCurrentAnimal()
    neighbour -->t -- : a
    t -> w ++: hit(a)
    w-->t --
ref over w, a
wave hits
end ref
end

[<-- t
deactivate t

@enduml