@startuml
participant "o : Orangutan" as o
participant "p : Panda" as p
participant "a: Panda" as a

[-> o: collideWithAnimal(p)
activate o

o-> p ++ : collideWithOrangutan(o)
p->p ++ : startLeading(o)
p->o: getGuidedAnimal()
o-->p: a
opt a!=null

p->p ++ : setGuidedAnimal(a)
p--> p -- :
p->a ++ : setLeaderAnimal(p)
a-->p --
end
p->o ++: setGuidedAnimal(p)
o-->p --
p-->p --
p -->o --

[<--o
deactivate o

@enduml